#!/bin/sh

PIDFILE=/tmp/aesdsocket.pid

case "$1" in
    start)
        echo "Starting aesdsocket..."
        start-stop-daemon --start \
			--name aesdsocket \
			--pidfile $PIDFILE \
			--startas /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket..."
        start-stop-daemon --stop \
			--name aesdsocket \
			--pidfile $PIDFILE \
			--retry 5 \
			--remove-pidfile
        ;;
    *)
        echo "Default: $0 {start|stop}"

    exit 1
esac

exit 0
